import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Baby,
  Bandage,
  Banknote,
  BarChart3,
  Bell,
  Bone,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ClipboardList,
  Clock,
  DoorOpen,
  Download,
  Dumbbell,
  FlaskConical,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Hospital,
  Inbox,
  LogOut,
  Mail,
  Menu,
  Microscope,
  Phone,
  Pill,
  Play,
  Radio,
  Receipt,
  Route,
  Scissors,
  Share2,
  Shield,
  Siren,
  Smile,
  Star,
  Stethoscope,
  User,
  UserRound,
  Users,
  Video,
  Wallet,
  X,
} from 'lucide-react';

const ICONS = {
  home: Home,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  clipboard: ClipboardList,
  pill: Pill,
  receipt: Receipt,
  video: Video,
  stethoscope: Stethoscope,
  users: Users,
  user: User,
  doctor: UserRound,
  route: Route,
  hospital: Hospital,
  building: Building2,
  chart: BarChart3,
  lock: Shield,
  microscope: Microscope,
  bandage: Bandage,
  bell: Bell,
  flask: FlaskConical,
  activity: Activity,
  door: DoorOpen,
  mail: Mail,
  inbox: Inbox,
  baby: Baby,
  heart: Heart,
  'heart-pulse': Heart,
  scissors: Scissors,
  radio: Radio,
  dumbbell: Dumbbell,
  tooth: Smile,
  bone: Bone,
  star: Star,
  check: Check,
  'check-circle': CheckCircle2,
  alert: AlertTriangle,
  clock: Clock,
  banknote: Banknote,
  wallet: Wallet,
  phone: Phone,
  download: Download,
  logout: LogOut,
  menu: Menu,
  close: X,
  'chevron-down': ChevronDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  siren: Siren,
  graduation: GraduationCap,
  facebook: Share2,
  instagram: Share2,
  twitter: Share2,
  play: Play,
  folder: ClipboardList,
  globe: Globe,
};

/**
 * Icône Lucide par nom (remplace les emojis dans l’UI).
 * @param {{ name: string, className?: string, size?: number, strokeWidth?: number }} props
 */
export default function Icon({ name, className = 'h-4 w-4', size, strokeWidth = 2, ...props }) {
  const Comp = ICONS[name] || Activity;
  return <Comp className={className} size={size} strokeWidth={strokeWidth} aria-hidden {...props} />;
}
