/**
 * Identité visuelle par rôle — chaque espace a sa palette, typo et libellés.
 * Médecin / infirmier gardent leurs layouts dédiés (MedecinLayout, InfirmierLayout).
 */

export const ROLE_THEMES = {
  patient: {
    id: 'patient',
    shellClass: 'patient-shell',
    displayFont: 'font-patient-display',
    brand: 'AMEN',
    spaceLabel: 'Espace patient',
    headerEyebrow: 'Mon suivi médical',
    roleLabel: 'Patient',
    sidebarFrom: '#1B3A2F',
    sidebarTo: '#142820',
    accent: '#3D8B6E',
    accentHover: '#32755C',
    accentSoft: '#D8EDE4',
    brandText: '#B8D9C8',
    muted: '#7A9A8A',
    navIdle: '#A8C4B4',
    contentBg: '#F3F7F4',
    headerBg: 'rgba(250,252,250,0.94)',
    headerBorder: '#D0E0D6',
    titleColor: '#1B3A2F',
    cardBorder: 'rgba(27,58,47,0.1)',
  },
  admin: {
    id: 'admin',
    shellClass: 'admin-shell',
    displayFont: 'font-admin-display',
    brand: 'AMEN',
    spaceLabel: 'Administration',
    headerEyebrow: 'Pilotage du centre',
    roleLabel: 'Administrateur',
    sidebarFrom: '#1C2433',
    sidebarTo: '#121821',
    accent: '#3B6FA0',
    accentHover: '#2F5A82',
    accentSoft: '#E2EBF4',
    brandText: '#A8C4DE',
    muted: '#8A9BB0',
    navIdle: '#B0BCC8',
    contentBg: '#EEF1F5',
    headerBg: 'rgba(248,250,252,0.94)',
    headerBorder: '#D5DCE6',
    titleColor: '#1C2433',
    cardBorder: 'rgba(28,36,51,0.1)',
  },
  receptionniste: {
    id: 'accueil',
    shellClass: 'accueil-shell',
    displayFont: 'font-accueil-display',
    brand: 'AMEN',
    spaceLabel: 'Accueil',
    headerEyebrow: 'Réception & orientation',
    roleLabel: 'Réceptionniste',
    sidebarFrom: '#0C3D4A',
    sidebarTo: '#0A303A',
    accent: '#1A9BB0',
    accentHover: '#158498',
    accentSoft: '#D6F0F4',
    brandText: '#9FD4DE',
    muted: '#6A9AA5',
    navIdle: '#A0C5CE',
    contentBg: '#EEF6F8',
    headerBg: 'rgba(247,252,253,0.94)',
    headerBorder: '#C5E0E6',
    titleColor: '#0C3D4A',
    cardBorder: 'rgba(12,61,74,0.1)',
  },
  laborantin: {
    id: 'labo',
    shellClass: 'labo-shell',
    displayFont: 'font-labo-display',
    brand: 'AMEN',
    spaceLabel: 'Laboratoire',
    headerEyebrow: 'Analyses & résultats',
    roleLabel: 'Laborantin',
    sidebarFrom: '#1A1F2E',
    sidebarTo: '#12151F',
    accent: '#C4A035',
    accentHover: '#A8882C',
    accentSoft: '#F5EED4',
    brandText: '#E0D4A0',
    muted: '#8A90A0',
    navIdle: '#B0B6C4',
    contentBg: '#F4F3EF',
    headerBg: 'rgba(252,251,248,0.94)',
    headerBorder: '#E0DCCE',
    titleColor: '#1A1F2E',
    cardBorder: 'rgba(26,31,46,0.1)',
  },
  pharmacien: {
    id: 'pharmacie',
    shellClass: 'pharmacie-shell',
    displayFont: 'font-pharmacie-display',
    brand: 'AMEN',
    spaceLabel: 'Pharmacie',
    headerEyebrow: 'Stock & délivrance',
    roleLabel: 'Pharmacien',
    sidebarFrom: '#0F3D2E',
    sidebarTo: '#0B2E22',
    accent: '#1F8A5B',
    accentHover: '#1A734C',
    accentSoft: '#D4F0E4',
    brandText: '#9FD4B8',
    muted: '#6A9A80',
    navIdle: '#A0C4B0',
    contentBg: '#F0F7F3',
    headerBg: 'rgba(247,252,249,0.94)',
    headerBorder: '#C5E0D0',
    titleColor: '#0F3D2E',
    cardBorder: 'rgba(15,61,46,0.1)',
  },
  caissier: {
    id: 'caisse',
    shellClass: 'caisse-shell',
    displayFont: 'font-caisse-display',
    brand: 'AMEN',
    spaceLabel: 'Caisse',
    headerEyebrow: 'Facturation & encaissement',
    roleLabel: 'Caissier',
    sidebarFrom: '#3A2818',
    sidebarTo: '#2A1C10',
    accent: '#C47A2C',
    accentHover: '#A86624',
    accentSoft: '#F5E6D4',
    brandText: '#E0C090',
    muted: '#A08868',
    navIdle: '#C4B090',
    contentBg: '#F7F2EB',
    headerBg: 'rgba(252,249,244,0.94)',
    headerBorder: '#E0D4C0',
    titleColor: '#3A2818',
    cardBorder: 'rgba(58,40,24,0.1)',
  },
  sage_femme: {
    id: 'maternite',
    shellClass: 'maternite-shell',
    displayFont: 'font-specialite-display',
    brand: 'AMEN',
    spaceLabel: 'Maternité',
    headerEyebrow: 'Suivi périnatal',
    roleLabel: 'Sage-femme',
    sidebarFrom: '#3A2030',
    sidebarTo: '#2A1522',
    accent: '#C45A7A',
    accentHover: '#A84A66',
    accentSoft: '#F5DCE4',
    brandText: '#E0A8B8',
    muted: '#A08090',
    navIdle: '#C4A0B0',
    contentBg: '#F8F0F3',
    headerBg: 'rgba(252,246,248,0.94)',
    headerBorder: '#E0C8D0',
    titleColor: '#3A2030',
    cardBorder: 'rgba(58,32,48,0.1)',
  },
  chirurgien: {
    id: 'chirurgie',
    shellClass: 'chirurgie-shell',
    displayFont: 'font-specialite-display',
    brand: 'AMEN',
    spaceLabel: 'Chirurgie',
    headerEyebrow: 'Bloc opératoire',
    roleLabel: 'Chirurgien',
    sidebarFrom: '#2A1A1A',
    sidebarTo: '#1A1010',
    accent: '#A04040',
    accentHover: '#863535',
    accentSoft: '#F0D8D8',
    brandText: '#D0A0A0',
    muted: '#907070',
    navIdle: '#C0A0A0',
    contentBg: '#F5F0F0',
    headerBg: 'rgba(250,246,246,0.94)',
    headerBorder: '#E0D0D0',
    titleColor: '#2A1A1A',
    cardBorder: 'rgba(42,26,26,0.1)',
  },
  anesthesiste: {
    id: 'chirurgie',
    shellClass: 'chirurgie-shell',
    displayFont: 'font-specialite-display',
    brand: 'AMEN',
    spaceLabel: 'Chirurgie',
    headerEyebrow: 'Anesthésie',
    roleLabel: 'Anesthésiste',
    sidebarFrom: '#2A1A1A',
    sidebarTo: '#1A1010',
    accent: '#A04040',
    accentHover: '#863535',
    accentSoft: '#F0D8D8',
    brandText: '#D0A0A0',
    muted: '#907070',
    navIdle: '#C0A0A0',
    contentBg: '#F5F0F0',
    headerBg: 'rgba(250,246,246,0.94)',
    headerBorder: '#E0D0D0',
    titleColor: '#2A1A1A',
    cardBorder: 'rgba(42,26,26,0.1)',
  },
  echographiste: {
    id: 'echo',
    shellClass: 'echo-shell',
    displayFont: 'font-specialite-display',
    brand: 'AMEN',
    spaceLabel: 'Échographie',
    headerEyebrow: 'Imagerie',
    roleLabel: 'Échographiste',
    sidebarFrom: '#1A2438',
    sidebarTo: '#12182A',
    accent: '#4A6FA5',
    accentHover: '#3C5A88',
    accentSoft: '#DCE4F0',
    brandText: '#A8B8D0',
    muted: '#7888A0',
    navIdle: '#A8B4C8',
    contentBg: '#F0F2F6',
    headerBg: 'rgba(248,249,252,0.94)',
    headerBorder: '#D0D6E0',
    titleColor: '#1A2438',
    cardBorder: 'rgba(26,36,56,0.1)',
  },
  kinesitherapeute: {
    id: 'kine',
    shellClass: 'kine-shell',
    displayFont: 'font-specialite-display',
    brand: 'AMEN',
    spaceLabel: 'Kinésithérapie',
    headerEyebrow: 'Rééducation',
    roleLabel: 'Kinésithérapeute',
    sidebarFrom: '#1A3328',
    sidebarTo: '#12241C',
    accent: '#4A9B6A',
    accentHover: '#3C8258',
    accentSoft: '#D8F0E0',
    brandText: '#A0D0B0',
    muted: '#709080',
    navIdle: '#A0C0B0',
    contentBg: '#F0F6F2',
    headerBg: 'rgba(247,252,248,0.94)',
    headerBorder: '#C8E0D0',
    titleColor: '#1A3328',
    cardBorder: 'rgba(26,51,40,0.1)',
  },
  dentiste: {
    id: 'dentisterie',
    shellClass: 'dentisterie-shell',
    displayFont: 'font-specialite-display',
    brand: 'AMEN',
    spaceLabel: 'Dentisterie',
    headerEyebrow: 'Soins dentaires',
    roleLabel: 'Dentiste',
    sidebarFrom: '#0E2F3A',
    sidebarTo: '#0A222A',
    accent: '#2A8FA8',
    accentHover: '#227890',
    accentSoft: '#D4EEF4',
    brandText: '#90C8D8',
    muted: '#6890A0',
    navIdle: '#A0C0D0',
    contentBg: '#EEF5F7',
    headerBg: 'rgba(246,251,252,0.94)',
    headerBorder: '#C5DCE4',
    titleColor: '#0E2F3A',
    cardBorder: 'rgba(14,47,58,0.1)',
  },
};

const MEDECIN_ROLES = [
  'medecin',
  'medecin_generaliste',
  'medecin_interne',
  'pediatre',
  'gynecologue',
  'ophtalmologue',
  'urgentiste',
];

/** @returns {'medecin'|'infirmier'|keyof typeof ROLE_THEMES|null} */
export function resolveShellKind(role) {
  if (!role) return null;
  if (MEDECIN_ROLES.includes(role)) return 'medecin';
  if (role === 'infirmier') return 'infirmier';
  if (ROLE_THEMES[role]) return role;
  return 'admin';
}

export function getRoleTheme(role) {
  const kind = resolveShellKind(role);
  if (kind === 'medecin' || kind === 'infirmier' || !kind) return null;
  return ROLE_THEMES[kind] || ROLE_THEMES.admin;
}

export { MEDECIN_ROLES };
